---
title: "Solutions for UKDD Challenges"
author: "Linh Dang"
format: html
editor: visual
---

## 

```{r}
#| echo: false
#| message: FALSE
library(Biostrings)
library(dplyr)
rm(list = ls())
```

## Challenge 1

```{r}
seqs <- Biostrings::readDNAStringSet("../data/KGE_DNA_test.fasta")

## write a function to call reverseComplement
get_reverseComplement <- function(input_DNAstring, start_idx=NA, end_idx=NA){
  ## input_DNAstring    --> DNAString object
  ## start_idx, end_idx --> integer within proper range: 1..length(seq)
  ##---------------------------------------------------
  ## check data type
  tmp_seq <- NA
  if(!"DNAString" %in% class(input_DNAstring)){
    stop("input_DNAstring has to be DNAString object")
  }
  ## check if index is integer
  if(is.na(start_idx) || is.na(end_idx)){
    print("Index is not valid, use a whole read instead!")
    tmp_seq <- 
  }
  
  ## check condition
  
  ## return value
  res <- input_DNAstring %>% 
    subseq(start = start_idx, end = end_idx) %>% 
    Biostrings::reverseComplement()
  return(res)
}

get_reverseComplement(seqs[[1]], 2, 10) %>% print()
```

## Challenge 2

Assumption two reads already aligned (have the same length)

```{r}
transition_lst <- c("AG", "GA", "CT", "TC")
transition_num  <- 0
transversion_num <- 0
S1 <- seqs[[1]] %>% as.character()
S2 <- seqs[[2]] %>% as.character()
for(i in 1:nchar(S1)){
  if(substr(S1,i,i) == substr(S2,i,i)){next}
  if(paste0(substr(S1,i,i), substr(S2, i, i)) %in% transition_lst){
    transition_num <- transition_num +1
  }else{
    transversion_num <- transversion_num +1
  }
}
R <- transition_num/transversion_num
print(sprintf("transition/transversion ratio is: %f", R))
```

## Challenge 3

```{r}
t <- "ACGTTGCA"
idxs <- gregexpr(t, seqs[[1]])[[1]] %>% as.vector()
print(t)
## double check
for(i in idxs){
  print(sprintf("Sub-string starts with an index: %i --> %s", i, substr(seqs[[1]], i, (i+nchar(t)-1))))
}
```

## Challenge 4

Find maximal repeat of a string

```{r}
Check_maximal_repeat(S, t, min_bp = 20){
  t_idx <- gregexpr2(pattern = t, text = S)[[1]]
  if(length(t_idx)<=1){
    return(FALSE)
  }
  if(!1 %in% t_idx){
    ## expand to the left
    tmp_t <- substr(S, t_idx[1]-1, t_idx[1]-1 + length(t))
  }
  if(1 %in% t_idx){
    ## can only expand to the right
    tmp_t <- substr(S, t_idx[1], t_idx[1] + length(t))
    tmp_idx <- gregexpr2(tmp_t, S)
    if(length(setdiff(t_idx, tmp_idx))==0){
      return(FALSE)
    }else{return(TRUE)}
  } 
}
S1 <- seqs[[1]] %>% as.character()
min_bp <- 20
until <- length(S1)-1

lst_maximal <- c()
## start from 1, go through the string
for(i in 1:until){
  t <- substr(S1, i, i+min_bp-1)
  t_idx <- gregexpr2(t, S1)[[1]]
  if(length(t_idx))
}
```

## Challenge 5

```{r}

```

## Challenge 6

```{r}

```
